# Generated by Django 3.2.18 on 2023-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('answered_correctly', models.BooleanField(default=False)),
            ],
        ),
    ]
