# Generated by Django 3.2.18 on 2023-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='date_answered',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answered_correctly',
            field=models.BooleanField(default=False),
        ),
    ]
